### PR TITLE
Update README.md

### LINKED ISSUE #15: TODO for v2 Release
Here's a short list of things we'll probably need to do to get this ready for publishing:

## Bare Minimum
 - [x] get `npm t` passing locally (fails on safari for me)
 - [x] Get CI passing (fails on ~~lint check it seems~~ now fails on saucelabs)
 - [ ] Totally rewrite the readme so it makes more sense.

## Probably should do:
 - [x] Update all deps/devdeps so we're in a good clean state

## Would be really nice to have
 - [x] Migrate to github actions and drop travis ci
 - [x] Separate lint check in GH Actions
 - [x] Separate node/browser tests in GH actions

## Stretch goals
 - [x] Migrate commitlint to github actions
 - [x] Migrate codecov to github actions checks

### PR DESCRIPTION
**Pull request by flaambe**
- Badges updated
- Install section rewritten

Closes #15

### CODE REVIEW

**Comment by flaambe** [comment]
I'm not sure that we should close #15, I thought we needed more improvements or it’s alright? @keithamus

**Comment by keithamus** [comment]
@flaambe I think it's good enough for a release. The readme is a little sparse, but it's not wrong

**Comment by flaambe** [comment]
I thought maybe update some dependencies, since some are already deprecated? @keithamus

**Comment by keithamus** [comment]
Oh okay sure! Do you want to raise a PR removing those?

**Comment by flaambe** [comment]
Yeah

**Pull request merged**
