### PR TITLE
use github actions

### PR DESCRIPTION
**Pull request by keithamus**

### CODE REVIEW

**Comment by flaambe** [comment]
@keithamus  It seems Windows test fails due to IE 11 doesn't support template literals

**Comment by keithamus** [comment]
IE 11 is important to support IMO. If we want to release this for Chai 4.x we need to support IE11 as Chai 4.x also supports IE11. We can transpile (or just avoid using) template literals.

I'd really like to get Edge 16-18 supported too - but it looks like theres a bug with Karma being unable to launch Microsoft Edge within Windows Server 2019 (which is what GitHub Actions use). Unsure how to get around this.

**Comment by flaambe** [comment]
I tried using ```babel-plugin-transform-es2015-template-literals```, but there was another error that I couldn’t figure out @keithamus

**Comment by flaambe** [comment]
@keithamus I have a question, why are we checking for AppVeyor and Travis in karma.conf and not just drop them?

**Comment by keithamus** [comment]
Now @lucasfcosta has approved I'll simply merge this in its broken state so we can resolve to fixing the issues around IE/Edge.

**Pull request merged**
