### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by flaambe**

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
LGTM

**Comment by flaambe** [comment]
@keithamus ie tests failing

**Comment by keithamus** [comment]
Have a v2 out is fine I think. We can simply release some patches. It hasn't been integrated with any of our libraries yet, so caveat emptor.

**Comment by flaambe** [comment]
Now version 2 is below version 1, how we can fix this?

**Comment by flaambe** [comment]
Now everything seems to be ok, only the version of karma I left 5.2.3, since the IE does not start on 6.0.1.

**Comment by keithamus** [comment]
> Do we really need all this deps?

Honestly I don't remember. I think they might be all peer deps of some plugin or rather?

**Pull request merged**
